<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "spurl"
 *
 * Auto generated by Extension Builder 2014-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'spURL',
	'description' => 'Easy to configure speaking URL translator with the possibility of nested, hierarchical elements.',
	'category' => 'plugin',
	'author' => 'Frederik Vosberg',
	'author_email' => 'frederik.vosberg@rattazonk.de',
	'author_company' => 'Rattazonk',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>